<?php

/**
 * @file
 * Defines all the hooks this module implements.
 *
 * islandora_daily_stats.module: defines paths as entry points and acts
 *  as a hub for dispatching tasks to other modules.
 *
 * This file is a utility module for use with Islandora.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the program.  If not, see <http ://www.gnu.org/licenses/>.
 */

// Permissions.
define('ISLANDORA_DAILY_STATS', 'use daily stats');

/**
 * Implements hook_menu().
 */
function islandora_daily_stats_menu() {
  return array(
    // top level general report summary - last week, last month snapshots
    'admin/reports/islandora/dailystats/summary' => array(
      'title' => 'Islandora Daily Stats Summary',
      'description' => 'Islandora Daily Stats - summary',
      'page callback' => array('islandora_daily_stats_summary_page'),
      'file' => 'includes/islandora_daily_stats_summary.page.inc',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
    'admin/reports/islandora/dailystats/stats/allmodels' => array(
//    'islandora/dailystats/%' => array(
      'title' => 'Islandora Daily Stats',
      'description' => 'Islandora Daily Stats',
      'page callback' => array('islandora_daily_stats_page'),
      'page arguments' => array(5),
      'file' => 'includes/islandora_daily_stats.page.inc',
      'type' => MENU_NORMAL_ITEM,
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
    'admin/reports/islandora/dailystats/stats/%' => array(
//    'islandora/dailystats/%' => array(
      'title' => 'Islandora Daily Stats',
      'description' => 'Islandora Daily Stats',
      'page callback' => array('islandora_daily_stats_page'),
      'page arguments' => array(5),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/islandora_daily_stats.page.inc',
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
    'admin/reports/islandora/dailystats/stats/%/%/%' => array(
      'title' => 'Islandora Daily Stats',
      'description' => 'Islandora Daily Stats',
      'page callback' => array('islandora_daily_stats_page'),
      'page arguments' => array(5, 6, 7),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'includes/islandora_daily_stats.page.inc',
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
  );
}

/**
 * Implements hook_presprocess_theme().
 *
 * This code will remove the sidebar and will add the stylesheet and js needed
 * for the report display.
 */
function islandora_daily_stats_preprocess_page(&$vars) {
  $item = menu_get_item();
  if (is_array($item)) {
    if ($item['path'] == 'admin/reports/islandora/dailystats/stats/%' ||
        $item['path'] == 'admin/reports/islandora/dailystats/summary' ||
        $item['path'] == 'admin/reports/islandora/dailystats/stats/allmodels') {
      drupal_add_js('https://www.gstatic.com/charts/loader.js');
      $module_path = drupal_get_path('module', 'islandora_daily_stats');
      drupal_add_css($module_path . '/css/islandora_daily_stats.css');
      $vars['sidebar'] = array();
    }
  }
}

/**
 * Implements hook_theme().
 */
function islandora_daily_stats_theme() {
  return array(
    'islandora_daily_stats_page' => array(
      'template' => 'theme/islandora-daily-stats-page',
      'variables' => array(
        'filter_links' => '',
        'models' => '',
        'values' => '',
        'dates' => '',
        'stats_table' => '',
      ),
    ),
    'islandora_daily_stats_summary_page' => array(
      'template' => 'theme/islandora-daily-stats-summary-page',
      'variables' => array(
        'filter_links' => '',
        'summary' => '',
      ),
    ),
    'islandora_daily_stats_summary_chart_js' => array(
      'template' => 'theme/islandora-daily-stats-summary-chart-js',
      'variables' => array(
        'values' => '',
      ),
    ),
    'islandora_daily_stats_overview_summary' => array(
      'template' => 'theme/islandora-daily-stats-overview-summary',
      'variables' => array(
        'name' => '',
        'description' => '',
        'today' => 0,
        'yesterday' => 0,
      ),
    ),
    'islandora_daily_stats_page_averages_summary' => array(
      'template' => 'theme/islandora-daily-stats-page_averages-summary',
      'variables' => array(
        'paged_models' => '',
      ),
    ),
    'islandora_daily_stats_model_summary' => array(
      'template' => 'theme/islandora-daily-stats-model-summary',
      'variables' => array(
        'name' => '',
        'total_today' => 0,
        'new_today' => 0,
        'new_in_last_week' => 0,
        'new_in_two_weeks' => 0,
        'new_in_last_month' => 0,
        'new_in_two_months' => 0,
        'prev_30_days' => 0,
        'yesterday_count' => 0,
        'last_7_count' => 0,
        'prev_7_days' => 0,
        'last_30_count' => 0,
        'last_30_days' => 0,
        'prev_30_days' => 0,
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_daily_stats_permission() {
  return array(
    ISLANDORA_DAILY_STATS => array(
      'title' => t('Use the Islandora Daily Stats'),
      'description' => t('User can use the Islandora Daily Stats.'),
    ),
  );
}
