<?php

// Permissions.
define('ISLANDORA_DAILY_STATS', 'use daily stats');

function islandora_daily_stats_menu() {
  return array(
    'islandora/dailystats/%' => array(
      'title' => 'Islandora Daily Stats',
      'description' => 'foo',
      'page callback' => array('islandora_daily_stats_page'),
      'page arguments' => array(2),
      'type' => MENU_CALLBACK,
      'file' => 'includes/islandora_daily_stats.page.inc',
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
    'islandora/dailystats/%/%/%' => array(
      'title' => 'Islandora Daily Stats',
      'description' => 'foo',
      'page callback' => array('islandora_daily_stats_page'),
      'page arguments' => array(2, 3, 4),
      'type' => MENU_CALLBACK,
      'file' => 'includes/islandora_daily_stats.page.inc',
      'access arguments' => array(ISLANDORA_DAILY_STATS),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_daily_stats_theme() {
  return array(
    // to remove duplicate pager and display_links
    'islandora_daily_stats_page' => array(
      'template' => 'theme/islandora-daily-stats-page',
      'variables' => array(
        'filter_links' => '',
        'stats_table' => '',
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_daily_stats_permission() {
  return array(
    ISLANDORA_DAILY_STATS => array(
      'title' => t('Use the Islandora Daily Stats'),
      'description' => t('User can use the Islandora Daily Stats.'),
    ),
  );
}
